BF: Yarik overdid msg in package_check
Kept msg with version even if package is not installed at all -- it is
better to let user know what minimal version to install.

Previous incorrect behavior lead to message becoming

RuntimeError: Nipype requires networkx with version >= 1.0 >= 1.0

git-svn-id: https://nipy.svn.sourceforge.net/svnroot/nipy/nipype/trunk@942 ead46cd0-7350-4e37-8683-fc4c6f79bf00